security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    in_memory_admin:
      memory:
        users:
          admin:
            password: '$2y$13$Phee2kQxiP/.zyMeGH1T9eo/ZUlt1abU8vfaVVNnPZhFv7ClkYZx.'
            roles: ['ROLE_ADMIN']

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: in_memory_admin
      http_basic:
        realm: 'Espace Admin Photovoltaique'

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
